version: '3'
services:
    php-fpm:
        build: ./php/
        ports:
          - "9000:9000"
        volumes:
          - ../www:/data/www:rw
          - ./php/php.ini:/usr/local/etc/php/php.ini:ro
          - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
          - ../logs/services:/data/service_logs/services:rw
        restart: always
        command: php-fpm

    nginx:
        build: ./nginx
        depends_on:
          - php-fpm
        links:
          - php-fpm:php-fpm
        volumes:
          - ../www:/data/www:ro
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
          - ../conf/nginx:/etc/nginx/conf.d:ro
          - ../logs/nginx:/data/logs/nginx
          - ../logs/services:/data/service_logs/services:rw
        ports:
          - "80:80"
          - "8080:8080"
          - "443:443"
        restart: always
        command: nginx -g 'daemon off;'

    redis:
       build: ./redis
       ports:
          - "6379:6379"
